### ISSUE TITLE
Recipe-api

### ISSUE THREAD

**Issue by Felipewithf** [Felipewithf/picnic_meal_planner#2]
- [ ] Fetch food recipe based on user input ( ingredients or full meals) we can select only one (ingredients) to decrease the complexity
- [ ] Load the first 3 selections
- [ ] Display the recipe _name_ of the 3 selections and image* (are image available with the recipes that is procure by the api??)
- [ ] Load the recipe _instructions_, _name_, and _ingredients_ on the recipe the user selected

**Comment by Vinoshan** [comment]
Got the Requirements will work on the next issue!
